---
- name: kernel_tuning | set view of bridges for netfilter
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_items:
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
    - { key: "net.bridge.bridge-nf-call-iptables", value: 1 }