---
- name: test os
  fail:
    msg: "Your OS {{ ansible_distribution }} v{{ ansible_distribution_major_version }} is not supported"
  when:
    (ansible_distribution != "Debian" and ansible_distribution_major_version|int >= 10) and
    (ansible_distribution != "CentOS" and ansible_distribution_major_version|int >= 7)